import pandas as pd
import csv

# Crear DataFrame con todos los datos UNESCO Ukraine
data = [
    {'id': 1, 'category': 'World Heritage List', 'name': 'Kyiv: Saint-Sophia Cathedral and Related Monastic Buildings Kyiv-Pechersk Lavra', 'type': 'Cultural', 'inscription_year': '1990', 'criteria': 'i, ii, iii, iv', 'location': 'Kyiv', 'description': 'Founded in the 11th century, this property includes the Saint-Sophia Cathedral and the Kyiv-Pechersk Lavra monastery complex. The cathedral preserves one of the world\'s largest ensembles of unique mosaics and frescoes from the first quarter of the 11th century. The monastery became the centre of Christianity in Kyivan Rus in the 11th century.', 'transnational': 'No', 'danger_list': 'Yes', 'danger_list_year': '2023', 'coordinates': '', 'extensions': ''},
    {'id': 2, 'category': 'World Heritage List', 'name': 'L\'viv – the Ensemble of the Historic Centre', 'type': 'Cultural', 'inscription_year': '1998', 'criteria': 'ii, v', 'location': 'Lviv', 'description': 'The city of L\'viv, founded in the late Middle Ages, was a flourishing administrative, religious and commercial centre for several centuries. The medieval urban topography has been preserved virtually intact, along with many fine Baroque and later buildings.', 'transnational': 'No', 'danger_list': 'Yes', 'danger_list_year': '2023', 'coordinates': '', 'extensions': ''},
    {'id': 3, 'category': 'World Heritage List', 'name': 'Struve Geodetic Arc', 'type': 'Cultural', 'inscription_year': '2005', 'criteria': 'ii, iv, vi', 'location': 'Multiple locations', 'description': 'The Struve Arc is a chain of survey triangulations stretching from Hammerfest in Norway to the Black Sea, through ten countries and over 2,820 km. These are points of a survey, carried out between 1816 and 1855 by the astronomer Friedrich Georg Wilhelm Struve, which represented the first accurate measuring of a long segment of a meridian.', 'transnational': 'Yes (10 countries: Norway, Sweden, Finland, Russia, Estonia, Latvia, Lithuania, Belarus, Moldova, Ukraine)', 'danger_list': 'No', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 4, 'category': 'World Heritage List', 'name': 'Residence of Bukovinian and Dalmatian Metropolitans', 'type': 'Cultural', 'inscription_year': '2011', 'criteria': 'ii, iii, iv', 'location': 'Chernivtsi', 'description': 'The Residence, built between 1864 and 1882 by Czech architect Josef Hlavka, represents a masterful synergy of architectural styles and building craftsmanship. The property, an outstanding example of 19th-century historicist architecture, also includes a seminary and monastery, illustrating the cultural identity of Orthodox Christianity.', 'transnational': 'No', 'danger_list': 'No', 'danger_list_year': '', 'coordinates': '48.2908 N 25.9353 E', 'extensions': ''},
    {'id': 5, 'category': 'World Heritage List', 'name': 'Ancient City of Tauric Chersonese and its Chora', 'type': 'Cultural', 'inscription_year': '2013', 'criteria': 'ii, v', 'location': 'Crimea (Sevastopol)', 'description': 'Founded by Dorian Greeks in the 5th century BC on the northern shores of the Black Sea. The site features remains of a polis with urban structures and agricultural lands divided into several hundreds of chora (rectangular plots). The city thrived until the 15th century as a productive wine centre and hub of exchange between Greek, Roman and Byzantine Empires.', 'transnational': 'No', 'danger_list': 'No', 'danger_list_year': '', 'coordinates': '44.6108 N, 33.4914 E', 'extensions': ''},
    {'id': 6, 'category': 'World Heritage List', 'name': 'Wooden Tserkvas of the Carpathian Region in Poland and Ukraine', 'type': 'Cultural', 'inscription_year': '2013', 'criteria': 'iii, iv', 'location': 'Carpathian region', 'description': 'Situated in the eastern fringe of Central Europe, sixteen wooden tserkvas (churches) were built between the 16th and 19th centuries by communities of Orthodox and Greek Catholic faiths. They represent outstanding examples of vernacular religious architecture, which integrates characteristic elements of Byzantine tradition with local traditions.', 'transnational': 'Yes (Poland and Ukraine)', 'danger_list': 'No', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 7, 'category': 'World Heritage List', 'name': 'Ancient and Primeval Beech Forests of the Carpathians and Other Regions of Europe', 'type': 'Natural', 'inscription_year': '2007 (extended 2011/2017/2021)', 'criteria': 'ix', 'location': 'Carpathian region', 'description': 'This transnational property includes examples of undisturbed temperate forests that demonstrate the postglacial expansion process of European beech. The Ukrainian components are located in the Carpathian Biosphere Reserve and include the Uholka-Shyrokyi Luh and Svydovets areas.', 'transnational': 'Yes (18 countries: Albania, Austria, Belgium, Bosnia and Herzegovina, Bulgaria, Croatia, Czechia, France, Germany, Italy, North Macedonia, Poland, Romania, Slovakia, Slovenia, Spain, Switzerland, Ukraine)', 'danger_list': 'No', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 8, 'category': 'World Heritage List', 'name': 'The Historic Centre of Odesa', 'type': 'Cultural', 'inscription_year': '2023', 'criteria': 'ii, iv', 'location': 'Odesa', 'description': 'A cosmopolitan port city on the Black Sea, Odesa reflects the successful fusion of different cultural influences. The city was founded at the end of the 18th century by Catherine II and became an important trading gateway and a cultural melting pot.', 'transnational': 'No', 'danger_list': 'Yes', 'danger_list_year': '2023', 'coordinates': '', 'extensions': ''},
    {'id': 9, 'category': 'Tentative List', 'name': 'Historic Centre of Tchernigov 9th-13th centuries', 'type': 'Cultural', 'inscription_year': 'Submitted 2006', 'criteria': '', 'location': 'Chernihiv, Chernihiv Oblast', 'description': 'Historic urban landscape built between the 9th and 13th centuries. Deeply affected in early months of 2022 war. UNESCO assisting with rehabilitation plan.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 10, 'category': 'Tentative List', 'name': 'Complex of the Sudak Fortress Monuments of the 6th-16th c.', 'type': 'Cultural', 'inscription_year': 'Submitted 2006', 'criteria': '', 'location': 'Sudak Crimea', 'description': 'Medieval defensive architecture highlighting fortifications from the 6th to 16th centuries. Located in occupied Crimea.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 11, 'category': 'Tentative List', 'name': 'Kyiv: Saint Sophia Cathedral with Related Monastic Buildings St. Cyril\'s and St. Andrew\'s Churches Kyiv-Pechersk Lavra', 'type': 'Cultural', 'inscription_year': 'Submitted 2016', 'criteria': '', 'location': 'Kyiv, Kyiv Oblast', 'description': 'Proposed extension of existing World Heritage site to include additional churches of historic and architectural significance.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 12, 'category': 'Tentative List', 'name': 'Trading Posts and Fortifications on Genoese Trade Routes from the Mediterranean to the Black Sea', 'type': 'Cultural', 'inscription_year': 'Submitted 2020', 'criteria': '', 'location': 'Multiple locations', 'description': 'Serial transnational nomination documenting Genoese commercial and military architecture along medieval trade routes.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 13, 'category': 'Tentative List', 'name': 'Khan\'s Palace in Bakhchysarai', 'type': 'Cultural', 'inscription_year': '', 'criteria': '', 'location': 'Bakhchysarai Crimea', 'description': 'Former residence of Crimean Khans. Located in occupied Crimea.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 14, 'category': 'Tentative List', 'name': 'Genoese Fortress in Balaklava', 'type': 'Cultural', 'inscription_year': '', 'criteria': '', 'location': 'Balaklava Crimea', 'description': 'Medieval Genoese fortification. Located in occupied Crimea.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 15, 'category': 'Tentative List', 'name': 'Kamyanets-Podilsky Historic Centre', 'type': 'Cultural', 'inscription_year': '', 'criteria': '', 'location': 'Kamyanets-Podilsky Khmelnytskyi Oblast', 'description': 'Historic fortified city with well-preserved medieval and early modern architecture.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 16, 'category': 'Tentative List', 'name': 'Sophia of Kyiv – Grand Cultural Capital', 'type': 'Cultural', 'inscription_year': '', 'criteria': '', 'location': 'Kyiv', 'description': 'Proposed expansion focusing on Sophia Cathedral complex and surrounding cultural landscape.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 17, 'category': 'Tentative List', 'name': 'Pochayiv Lavra', 'type': 'Cultural', 'inscription_year': '', 'criteria': '', 'location': 'Pochayiv Ternopil Oblast', 'description': 'Important Orthodox monastery and pilgrimage site.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 18, 'category': 'Tentative List', 'name': 'Medieval Fortresses in the Ukrainian Carpathians', 'type': 'Cultural', 'inscription_year': '', 'criteria': '', 'location': 'Carpathian region', 'description': 'System of medieval defensive structures in the Carpathian Mountains.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 19, 'category': 'Tentative List', 'name': 'Taras Shevchenko\'s Grave', 'type': 'Cultural', 'inscription_year': '', 'criteria': '', 'location': 'Kaniv Cherkasy Oblast', 'description': 'Memorial site of Ukraine\'s national poet. Granted UNESCO enhanced protection in 2023.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 20, 'category': 'Tentative List', 'name': 'Historic Centres of Kremenets and Zbarazh', 'type': 'Cultural', 'inscription_year': '', 'criteria': '', 'location': 'Ternopil Oblast', 'description': 'Historic urban ensembles with significant architectural heritage.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 21, 'category': 'Tentative List', 'name': 'Kachanivka Palace and Park Ensemble', 'type': 'Cultural', 'inscription_year': '', 'criteria': '', 'location': 'Ichnia Chernihiv Oblast', 'description': '18th-19th century palace complex with landscape park.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 22, 'category': 'Tentative List', 'name': 'Dormition Cathedral Pochaiv', 'type': 'Cultural', 'inscription_year': '', 'criteria': '', 'location': 'Pochayiv Ternopil Oblast', 'description': 'Historic cathedral within Pochayiv Lavra complex.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 23, 'category': 'Tentative List', 'name': 'Dniester Canyon', 'type': 'Natural', 'inscription_year': '', 'criteria': '', 'location': 'Ternopil and Chernivtsi Oblasts', 'description': 'Unique natural canyon landscape along the Dniester River.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 24, 'category': 'Tentative List', 'name': 'Danube Biosphere Reserve', 'type': 'Natural', 'inscription_year': '', 'criteria': '', 'location': 'Odesa Oblast', 'description': 'Important wetland ecosystem at the Danube Delta.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 25, 'category': 'State of Conservation', 'name': 'Kyiv: Saint-Sophia Cathedral and Related Monastic Buildings Kyiv-Pechersk Lavra', 'type': '2023 Report', 'inscription_year': '', 'criteria': '', 'location': '', 'description': 'Under permanent threat since February 24 2022. Inscribed on List of World Heritage in Danger September 2023. Physical damage in buffer zone. Management plan development stalled due to war.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 26, 'category': 'State of Conservation', 'name': 'Kyiv: Saint-Sophia Cathedral and Related Monastic Buildings Kyiv-Pechersk Lavra', 'type': '2024 Report', 'inscription_year': '', 'criteria': '', 'location': '', 'description': 'Continued monitoring and protection efforts. Ongoing threats from armed conflict. Emergency preparedness measures implemented.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 27, 'category': 'State of Conservation', 'name': 'Kyiv: Saint-Sophia Cathedral and Related Monastic Buildings Kyiv-Pechersk Lavra', 'type': '2025 Report', 'inscription_year': '', 'criteria': '', 'location': '', 'description': 'Report submitted by State Party. Assessment ongoing.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 28, 'category': 'State of Conservation', 'name': 'L\'viv – the Ensemble of the Historic Centre', 'type': '2023 Report', 'inscription_year': '', 'criteria': '', 'location': '', 'description': 'Inscribed on List of World Heritage in Danger September 2023. Under permanent threat since February 24 2022. Vulnerable to shockwaves from bombing. Multiple protection measures implemented by Ukrainian authorities.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 29, 'category': 'State of Conservation', 'name': 'L\'viv – the Ensemble of the Historic Centre', 'type': '2024 Report', 'inscription_year': '', 'criteria': '', 'location': '', 'description': 'Continued protection and monitoring. Emergency response protocols in place. Training for cultural professionals.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 30, 'category': 'State of Conservation', 'name': 'L\'viv – the Ensemble of the Historic Centre', 'type': '2025 Report', 'inscription_year': '', 'criteria': '', 'location': '', 'description': 'Report submitted by State Party. Assessment ongoing.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 31, 'category': 'State of Conservation', 'name': 'The Historic Centre of Odesa', 'type': '2023 Report', 'inscription_year': '', 'criteria': '', 'location': '', 'description': 'Inscribed simultaneously on World Heritage List and List of World Heritage in Danger January 25 2023. Significant damage from aerial assaults including July 2023 strikes affecting museums. 52 cultural properties reported damaged of which 47 verified by UNESCO mission.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 32, 'category': 'State of Conservation', 'name': 'The Historic Centre of Odesa', 'type': '2024 Report', 'inscription_year': '', 'criteria': '', 'location': '', 'description': 'Major attacks November 14-15 2024 damaged historic buildings within property boundaries. Management plan development in progress with UNESCO-ICOMOS support. UNESCO-Japan Funds-in-Trust project providing USD 5.9 million for monitoring and emergency response. UNESCO-Italy project USD 530000 for protective roof on Transfiguration Cathedral.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 33, 'category': 'State of Conservation', 'name': 'The Historic Centre of Odesa', 'type': '2025 Report', 'inscription_year': '', 'criteria': '', 'location': '', 'description': 'Report submitted by State Party. Ongoing protection and rehabilitation efforts.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 34, 'category': 'State of Conservation', 'name': 'Ancient City of Tauric Chersonese and its Chora', 'type': '2016 Report', 'inscription_year': '', 'criteria': '', 'location': '', 'description': 'Critical state of conservation of ruins with high dilapidation. Some structures close to collapse. Located in occupied Crimea restricting UNESCO access since 2014.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 35, 'category': 'State of Conservation', 'name': 'Ancient and Primeval Beech Forests of the Carpathians and Other Regions of Europe', 'type': '2023 Report', 'inscription_year': '', 'criteria': '', 'location': '', 'description': 'Monitoring challenges due to war. No direct conflict damage reported to Ukrainian components as of 2023.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 36, 'category': 'State of Conservation', 'name': 'Ancient and Primeval Beech Forests of the Carpathians and Other Regions of Europe', 'type': '2025 Report', 'inscription_year': '', 'criteria': '', 'location': '', 'description': 'Continued monitoring within security constraints.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 37, 'category': 'General Information', 'name': 'Total World Heritage Sites in Ukraine', 'type': '8', 'inscription_year': '', 'criteria': '', 'location': '', 'description': '7 cultural and 1 natural site. 3 sites currently on List of World Heritage in Danger (Kyiv, Lviv, Odesa). 3 sites are transnational.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 38, 'category': 'General Information', 'name': 'Total Tentative List Sites', 'type': '16', 'inscription_year': '', 'criteria': '', 'location': '', 'description': '16 sites on Tentative List awaiting nomination. Several located in occupied territories.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 39, 'category': 'General Information', 'name': 'Enhanced Protection List', 'type': '27', 'inscription_year': '', 'criteria': '', 'location': '', 'description': '25 sites added to International List of Cultural Property Under Enhanced Protection in 2023. 2 additional sites (Babyn Yar Memorial and Odesa Literary Museum) added December 2024. Total 27 sites under enhanced protection.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 40, 'category': 'General Information', 'name': 'Verified Damage', 'type': '343 sites (as of 2024)', 'inscription_year': '', 'criteria': '', 'location': '', 'description': 'UNESCO verified damage to 343 cultural sites as of February 2024: 31 museums 127 religious sites 151 buildings of historical/artistic interest 19 monuments 14 libraries 1 archive. Worst affected regions: Donetsk (88 sites) Kharkiv (56 sites) Odesa (49 sites) Kyiv (39 sites) Luhansk (34 sites).', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 41, 'category': 'General Information', 'name': 'Recovery Costs', 'type': 'USD 9 billion', 'inscription_year': '', 'criteria': '', 'location': '', 'description': 'Estimated cost for recovery and reconstruction of culture and tourism sectors 2024-2033. Increased from USD 6.9 billion in 2023.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''},
    {'id': 42, 'category': 'General Information', 'name': 'UNESCO Funding', 'type': 'USD 66 million', 'inscription_year': '', 'criteria': '', 'location': '', 'description': 'UNESCO raised over USD 66 million from Member States and private sector over 2 years (2022-2024). Japan contributed almost USD 26 million.', 'transnational': '', 'danger_list': '', 'danger_list_year': '', 'coordinates': '', 'extensions': ''}
]

# Crear y guardar CSV
df = pd.DataFrame(data)
df.to_csv('unesco_ukraine.csv', index=False, encoding='utf-8', quoting=csv.QUOTE_NONNUMERIC)

print("✓ unesco_ukraine.csv creado exitosamente")
print(f"  {len(df)} registros")
print(f"  {len(df.columns)} columnas")